{% set name = "javabridge" %}
{% set version = "1.0.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/j/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bbb57f71356738f46dd34648f562047755c369f4a64dcfab92d5c7e2a97718aa

build:
  number: 3
  script: '{{ PYTHON }} -m pip install --no-deps --ignore-installed . '
  skip: true  # [win or osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - cython
    - openjdk 8*
  run:
    - python
    - numpy
    - openjdk 8*
  run_constrained:
    - python-javabridge =99999999

test:
  imports:
    - javabridge
    - javabridge.tests
  requires:
    - nose
    - openjdk

about:
  home: http://github.com/CellProfiler/python-javabridge/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Python wrapper for the Java Native Interface
  description: |
    The python-javabridge package makes it easy to start a Java virtual machine (JVM) from Python and interact with it. Python code can interact with the JVM using a low-level API or a more convenient high-level API. Python-javabridge was developed for and is used by cell image analysis software CellProfiler.
  doc_url: https://pythonhosted.org/javabridge/
  dev_url: http://github.com/CellProfiler/python-javabridge/

extra:
  recipe-maintainers:
    - sunyi000
    - raivivek
